name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Install composer dependencies
      uses: MilesChou/composer-action@master
      with:
        args: install --no-ansi --no-interaction --prefer-dist

    - name: PHP Runner
      uses: franzliedke/gh-action-php@0.2.0
